//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDataStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DAX_PRODEntities : DbContext
    {
        public DAX_PRODEntities()
            : base("name=DAX_PRODEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<VMI_Get_Users_Result> VMI_Get_Users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VMI_Get_Users_Result>("VMI_Get_Users");
        }
    
        public virtual ObjectResult<VMI_Get_Users_Customers_Result> VMI_Get_Users_Customers(string uSER_ID)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VMI_Get_Users_Customers_Result>("VMI_Get_Users_Customers", uSER_IDParameter);
        }
    
        public virtual ObjectResult<VMI_GetOrderCases_Result> VMI_GetOrderCases(string cUSTOMER, string sKU)
        {
            var cUSTOMERParameter = cUSTOMER != null ?
                new ObjectParameter("CUSTOMER", cUSTOMER) :
                new ObjectParameter("CUSTOMER", typeof(string));
    
            var sKUParameter = sKU != null ?
                new ObjectParameter("SKU", sKU) :
                new ObjectParameter("SKU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VMI_GetOrderCases_Result>("VMI_GetOrderCases", cUSTOMERParameter, sKUParameter);
        }
    
        public virtual ObjectResult<VMI_GetUserInfo_Result> VMI_GetUserInfo(string nETWORKALIAS)
        {
            var nETWORKALIASParameter = nETWORKALIAS != null ?
                new ObjectParameter("NETWORKALIAS", nETWORKALIAS) :
                new ObjectParameter("NETWORKALIAS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VMI_GetUserInfo_Result>("VMI_GetUserInfo", nETWORKALIASParameter);
        }
    
        public virtual ObjectResult<DBI_GetBannerByDirectCustomer_Result> DBI_GetBannerByDirectCustomer(string directCustomerNumber)
        {
            var directCustomerNumberParameter = directCustomerNumber != null ?
                new ObjectParameter("DirectCustomerNumber", directCustomerNumber) :
                new ObjectParameter("DirectCustomerNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DBI_GetBannerByDirectCustomer_Result>("DBI_GetBannerByDirectCustomer", directCustomerNumberParameter);
        }
    
        public virtual ObjectResult<FORECASTER_GET_ACTUAL_ORDERS_BY_SALES_ORDER_ID_Result> FORECASTER_GET_ACTUAL_ORDERS_BY_SALES_ORDER_ID(string cUSTOMERID, string sALES_ORDER_ID)
        {
            var cUSTOMERIDParameter = cUSTOMERID != null ?
                new ObjectParameter("CUSTOMERID", cUSTOMERID) :
                new ObjectParameter("CUSTOMERID", typeof(string));
    
            var sALES_ORDER_IDParameter = sALES_ORDER_ID != null ?
                new ObjectParameter("SALES_ORDER_ID", sALES_ORDER_ID) :
                new ObjectParameter("SALES_ORDER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FORECASTER_GET_ACTUAL_ORDERS_BY_SALES_ORDER_ID_Result>("FORECASTER_GET_ACTUAL_ORDERS_BY_SALES_ORDER_ID", cUSTOMERIDParameter, sALES_ORDER_IDParameter);
        }
    
        public virtual ObjectResult<FORECASTER_GET_CUSTOMER_INFORMATION_Result> FORECASTER_GET_CUSTOMER_INFORMATION(string cUSTOMERID)
        {
            var cUSTOMERIDParameter = cUSTOMERID != null ?
                new ObjectParameter("CUSTOMERID", cUSTOMERID) :
                new ObjectParameter("CUSTOMERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FORECASTER_GET_CUSTOMER_INFORMATION_Result>("FORECASTER_GET_CUSTOMER_INFORMATION", cUSTOMERIDParameter);
        }
    
        public virtual ObjectResult<FORECASTER_GET_ORDERS_STATUSES_Result> FORECASTER_GET_ORDERS_STATUSES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FORECASTER_GET_ORDERS_STATUSES_Result>("FORECASTER_GET_ORDERS_STATUSES");
        }
    
        public virtual ObjectResult<FORECASTER_GET_ACTUAL_ORDERS_Result> FORECASTER_GET_ACTUAL_ORDERS(string cUSTOMERID, Nullable<int> lAST_YEAR)
        {
            var cUSTOMERIDParameter = cUSTOMERID != null ?
                new ObjectParameter("CUSTOMERID", cUSTOMERID) :
                new ObjectParameter("CUSTOMERID", typeof(string));
    
            var lAST_YEARParameter = lAST_YEAR.HasValue ?
                new ObjectParameter("LAST_YEAR", lAST_YEAR) :
                new ObjectParameter("LAST_YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FORECASTER_GET_ACTUAL_ORDERS_Result>("FORECASTER_GET_ACTUAL_ORDERS", cUSTOMERIDParameter, lAST_YEARParameter);
        }
    }
}
