//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDataStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DaisyDWEntities : DbContext
    {
        public DaisyDWEntities()
            : base("name=DaisyDWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<FORECASTER_Get_KrogerPOSData_Result> FORECASTER_Get_KrogerPOSData(string dIVISION_NUMBER)
        {
            var dIVISION_NUMBERParameter = dIVISION_NUMBER != null ?
                new ObjectParameter("DIVISION_NUMBER", dIVISION_NUMBER) :
                new ObjectParameter("DIVISION_NUMBER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FORECASTER_Get_KrogerPOSData_Result>("FORECASTER_Get_KrogerPOSData", dIVISION_NUMBERParameter);
        }
    }
}
