//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDataStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dbidbEntities : DbContext
    {
        public dbidbEntities()
            : base("name=dbidbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<string> VMI_Get_Customers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VMI_Get_Customers");
        }
    
        public virtual ObjectResult<VMI_Get_Customers_QS_Amounts_by_period_Result> VMI_Get_Customers_QS_Amounts_by_period(string cUSTOMER_ID, string sKUID, Nullable<System.DateTime> sTART, Nullable<System.DateTime> eND)
        {
            var cUSTOMER_IDParameter = cUSTOMER_ID != null ?
                new ObjectParameter("CUSTOMER_ID", cUSTOMER_ID) :
                new ObjectParameter("CUSTOMER_ID", typeof(string));
    
            var sKUIDParameter = sKUID != null ?
                new ObjectParameter("SKUID", sKUID) :
                new ObjectParameter("SKUID", typeof(string));
    
            var sTARTParameter = sTART.HasValue ?
                new ObjectParameter("START", sTART) :
                new ObjectParameter("START", typeof(System.DateTime));
    
            var eNDParameter = eND.HasValue ?
                new ObjectParameter("END", eND) :
                new ObjectParameter("END", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VMI_Get_Customers_QS_Amounts_by_period_Result>("VMI_Get_Customers_QS_Amounts_by_period", cUSTOMER_IDParameter, sKUIDParameter, sTARTParameter, eNDParameter);
        }
    
        public virtual ObjectResult<VMI_Get_Customers_Quantity_Amounts_Result> VMI_Get_Customers_Quantity_Amounts(string cUSTOMER_ID, string sKUID, Nullable<int> lAST_YEAR_QUERIED)
        {
            var cUSTOMER_IDParameter = cUSTOMER_ID != null ?
                new ObjectParameter("CUSTOMER_ID", cUSTOMER_ID) :
                new ObjectParameter("CUSTOMER_ID", typeof(string));
    
            var sKUIDParameter = sKUID != null ?
                new ObjectParameter("SKUID", sKUID) :
                new ObjectParameter("SKUID", typeof(string));
    
            var lAST_YEAR_QUERIEDParameter = lAST_YEAR_QUERIED.HasValue ?
                new ObjectParameter("LAST_YEAR_QUERIED", lAST_YEAR_QUERIED) :
                new ObjectParameter("LAST_YEAR_QUERIED", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VMI_Get_Customers_Quantity_Amounts_Result>("VMI_Get_Customers_Quantity_Amounts", cUSTOMER_IDParameter, sKUIDParameter, lAST_YEAR_QUERIEDParameter);
        }
    
        public virtual ObjectResult<VMI_Get_Customers_SkuIds_Result> VMI_Get_Customers_SkuIds(Nullable<int> lAST_YEAR_QUERIED)
        {
            var lAST_YEAR_QUERIEDParameter = lAST_YEAR_QUERIED.HasValue ?
                new ObjectParameter("LAST_YEAR_QUERIED", lAST_YEAR_QUERIED) :
                new ObjectParameter("LAST_YEAR_QUERIED", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VMI_Get_Customers_SkuIds_Result>("VMI_Get_Customers_SkuIds", lAST_YEAR_QUERIEDParameter);
        }
    
        public virtual ObjectResult<VMI_Get_Performance_By_CustomerAccountNum_Result> VMI_Get_Performance_By_CustomerAccountNum(string cUSTOMER_ACCOUNT_NUM, string sKUID)
        {
            var cUSTOMER_ACCOUNT_NUMParameter = cUSTOMER_ACCOUNT_NUM != null ?
                new ObjectParameter("CUSTOMER_ACCOUNT_NUM", cUSTOMER_ACCOUNT_NUM) :
                new ObjectParameter("CUSTOMER_ACCOUNT_NUM", typeof(string));
    
            var sKUIDParameter = sKUID != null ?
                new ObjectParameter("SKUID", sKUID) :
                new ObjectParameter("SKUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VMI_Get_Performance_By_CustomerAccountNum_Result>("VMI_Get_Performance_By_CustomerAccountNum", cUSTOMER_ACCOUNT_NUMParameter, sKUIDParameter);
        }
    
        public virtual ObjectResult<VMI_Get_Customers_Quantity_Amounts_Up_Last_Date_Result> VMI_Get_Customers_Quantity_Amounts_Up_Last_Date(string cUSTOMER_ID, string sKUID, Nullable<System.DateTime> lAST_DATE_QUERIED)
        {
            var cUSTOMER_IDParameter = cUSTOMER_ID != null ?
                new ObjectParameter("CUSTOMER_ID", cUSTOMER_ID) :
                new ObjectParameter("CUSTOMER_ID", typeof(string));
    
            var sKUIDParameter = sKUID != null ?
                new ObjectParameter("SKUID", sKUID) :
                new ObjectParameter("SKUID", typeof(string));
    
            var lAST_DATE_QUERIEDParameter = lAST_DATE_QUERIED.HasValue ?
                new ObjectParameter("LAST_DATE_QUERIED", lAST_DATE_QUERIED) :
                new ObjectParameter("LAST_DATE_QUERIED", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VMI_Get_Customers_Quantity_Amounts_Up_Last_Date_Result>("VMI_Get_Customers_Quantity_Amounts_Up_Last_Date", cUSTOMER_IDParameter, sKUIDParameter, lAST_DATE_QUERIEDParameter);
        }
    }
}
