//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORECASTER_KROGER_DIVISION_LIST
    {
        public int ID { get; set; }
        public string MARKET { get; set; }
        public string NAME { get; set; }
        public string DC { get; set; }
        public int TP { get; set; }
    }
}
