//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORECASTER_COMMENT_TABLE
    {
        public int COMMENTID { get; set; }
        public string WEEKID { get; set; }
        public string ITEM_UPC { get; set; }
        public int SHIP_TO_TP { get; set; }
        public string VALUE { get; set; }
        public string ENTERED_BY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
    }
}
