//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORECASTER_CUSTOMER_SETTINGS
    {
        public int CUSTOMER_ID { get; set; }
        public string LINK { get; set; }
        public string STORE_COUNT { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> REPORTING_DAYS { get; set; }
        public string REPORTING_START { get; set; }
        public string REPORTING_END { get; set; }
        public Nullable<bool> WILL_COVER_ORDER_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public string ENTERED_BY { get; set; }
    }
}
