//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORECASTER_EVENTLOGS
    {
        public int ID { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string USER_ID { get; set; }
        public string MESSAGE { get; set; }
        public string VALUE { get; set; }
        public System.DateTime CREATED { get; set; }
    }
}
