//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORECASTER_FORECAST_TABLE
    {
        public int FORECASTID { get; set; }
        public string WEEKID { get; set; }
        public string ITEM_UPC { get; set; }
        public int SHIP_TO_TP { get; set; }
        public int VALUE { get; set; }
        public Nullable<int> QA { get; set; }
        public Nullable<int> QS { get; set; }
        public Nullable<int> QO { get; set; }
        public Nullable<int> QW { get; set; }
        public Nullable<int> QC { get; set; }
        public Nullable<int> QD { get; set; }
        public string ENTERED_BY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string FORMULA { get; set; }
        public string L4WKAVGTRN { get; set; }
        public string L13WKAVGTRN { get; set; }
        public Nullable<int> BASELINE { get; set; }
    }
}
