//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORECASTER_PERFORMANCES_EXCEPTIONS
    {
        public System.Guid GUID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string SKU { get; set; }
        public string TYPE { get; set; }
        public System.DateTime FROM { get; set; }
        public System.DateTime TO { get; set; }
        public int QUANTITY { get; set; }
        public double PRICE { get; set; }
        public string DESCRIPTION { get; set; }
        public bool INCLUDE { get; set; }
        public bool IS_DEFAULT { get; set; }
        public Nullable<int> STATE { get; set; }
        public string STATE_USER { get; set; }
        public Nullable<System.DateTime> STATE_LAST_UPDATED { get; set; }
    }
}
