//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORECASTER_CUSTOMER_SKU_SETTINGS
    {
        public int CUSTOMER_ID { get; set; }
        public string SKU { get; set; }
        public Nullable<double> SAFETY_STOCK_DAYS { get; set; }
        public Nullable<double> AVG_PRICE_POINT { get; set; }
        public string STORE_COUNT { get; set; }
        public string COMMENT { get; set; }
        public string OCOMMENT { get; set; }
        public string ITEM_NUM { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public string ENTERED_BY { get; set; }
    }
}
