//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORECASTER_TIE_LIST
    {
        public string ITEM_UPC { get; set; }
        public int TIE { get; set; }
    }
}
