//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daisybrand.forecaster.Services.Email {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://daisybrand/webservices/", ConfigurationName="Services.Email.EmailServiceSoap")]
    public interface EmailServiceSoap {
        
        // CODEGEN: Generating message contract since element name from from namespace http://daisybrand/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://daisybrand/webservices/SendMail", ReplyAction="*")]
        daisybrand.forecaster.Services.Email.SendMailResponse SendMail(daisybrand.forecaster.Services.Email.SendMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://daisybrand/webservices/SendMail", ReplyAction="*")]
        System.Threading.Tasks.Task<daisybrand.forecaster.Services.Email.SendMailResponse> SendMailAsync(daisybrand.forecaster.Services.Email.SendMailRequest request);
        
        // CODEGEN: Generating message contract since element name from from namespace http://daisybrand/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://daisybrand/webservices/SendMailWithAttachment", ReplyAction="*")]
        daisybrand.forecaster.Services.Email.SendMailWithAttachmentResponse SendMailWithAttachment(daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://daisybrand/webservices/SendMailWithAttachment", ReplyAction="*")]
        System.Threading.Tasks.Task<daisybrand.forecaster.Services.Email.SendMailWithAttachmentResponse> SendMailWithAttachmentAsync(daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMail", Namespace="http://daisybrand/webservices/", Order=0)]
        public daisybrand.forecaster.Services.Email.SendMailRequestBody Body;
        
        public SendMailRequest() {
        }
        
        public SendMailRequest(daisybrand.forecaster.Services.Email.SendMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://daisybrand/webservices/")]
    public partial class SendMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string body;
        
        public SendMailRequestBody() {
        }
        
        public SendMailRequestBody(string from, string to, string cc, string bcc, string subject, string body) {
            this.from = from;
            this.to = to;
            this.cc = cc;
            this.bcc = bcc;
            this.subject = subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailResponse", Namespace="http://daisybrand/webservices/", Order=0)]
        public daisybrand.forecaster.Services.Email.SendMailResponseBody Body;
        
        public SendMailResponse() {
        }
        
        public SendMailResponse(daisybrand.forecaster.Services.Email.SendMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendMailResponseBody {
        
        public SendMailResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailWithAttachmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailWithAttachment", Namespace="http://daisybrand/webservices/", Order=0)]
        public daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequestBody Body;
        
        public SendMailWithAttachmentRequest() {
        }
        
        public SendMailWithAttachmentRequest(daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://daisybrand/webservices/")]
    public partial class SendMailWithAttachmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string attachment;
        
        public SendMailWithAttachmentRequestBody() {
        }
        
        public SendMailWithAttachmentRequestBody(string from, string to, string cc, string bcc, string subject, string body, string attachment) {
            this.from = from;
            this.to = to;
            this.cc = cc;
            this.bcc = bcc;
            this.subject = subject;
            this.body = body;
            this.attachment = attachment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailWithAttachmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailWithAttachmentResponse", Namespace="http://daisybrand/webservices/", Order=0)]
        public daisybrand.forecaster.Services.Email.SendMailWithAttachmentResponseBody Body;
        
        public SendMailWithAttachmentResponse() {
        }
        
        public SendMailWithAttachmentResponse(daisybrand.forecaster.Services.Email.SendMailWithAttachmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendMailWithAttachmentResponseBody {
        
        public SendMailWithAttachmentResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmailServiceSoapChannel : daisybrand.forecaster.Services.Email.EmailServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailServiceSoapClient : System.ServiceModel.ClientBase<daisybrand.forecaster.Services.Email.EmailServiceSoap>, daisybrand.forecaster.Services.Email.EmailServiceSoap {
        
        public EmailServiceSoapClient() {
        }
        
        public EmailServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        daisybrand.forecaster.Services.Email.SendMailResponse daisybrand.forecaster.Services.Email.EmailServiceSoap.SendMail(daisybrand.forecaster.Services.Email.SendMailRequest request) {
            return base.Channel.SendMail(request);
        }
        
        public void SendMail(string from, string to, string cc, string bcc, string subject, string body) {
            daisybrand.forecaster.Services.Email.SendMailRequest inValue = new daisybrand.forecaster.Services.Email.SendMailRequest();
            inValue.Body = new daisybrand.forecaster.Services.Email.SendMailRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            daisybrand.forecaster.Services.Email.SendMailResponse retVal = ((daisybrand.forecaster.Services.Email.EmailServiceSoap)(this)).SendMail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<daisybrand.forecaster.Services.Email.SendMailResponse> daisybrand.forecaster.Services.Email.EmailServiceSoap.SendMailAsync(daisybrand.forecaster.Services.Email.SendMailRequest request) {
            return base.Channel.SendMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<daisybrand.forecaster.Services.Email.SendMailResponse> SendMailAsync(string from, string to, string cc, string bcc, string subject, string body) {
            daisybrand.forecaster.Services.Email.SendMailRequest inValue = new daisybrand.forecaster.Services.Email.SendMailRequest();
            inValue.Body = new daisybrand.forecaster.Services.Email.SendMailRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            return ((daisybrand.forecaster.Services.Email.EmailServiceSoap)(this)).SendMailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        daisybrand.forecaster.Services.Email.SendMailWithAttachmentResponse daisybrand.forecaster.Services.Email.EmailServiceSoap.SendMailWithAttachment(daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequest request) {
            return base.Channel.SendMailWithAttachment(request);
        }
        
        public void SendMailWithAttachment(string from, string to, string cc, string bcc, string subject, string body, string attachment) {
            daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequest inValue = new daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequest();
            inValue.Body = new daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.attachment = attachment;
            daisybrand.forecaster.Services.Email.SendMailWithAttachmentResponse retVal = ((daisybrand.forecaster.Services.Email.EmailServiceSoap)(this)).SendMailWithAttachment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<daisybrand.forecaster.Services.Email.SendMailWithAttachmentResponse> daisybrand.forecaster.Services.Email.EmailServiceSoap.SendMailWithAttachmentAsync(daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequest request) {
            return base.Channel.SendMailWithAttachmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<daisybrand.forecaster.Services.Email.SendMailWithAttachmentResponse> SendMailWithAttachmentAsync(string from, string to, string cc, string bcc, string subject, string body, string attachment) {
            daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequest inValue = new daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequest();
            inValue.Body = new daisybrand.forecaster.Services.Email.SendMailWithAttachmentRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.attachment = attachment;
            return ((daisybrand.forecaster.Services.Email.EmailServiceSoap)(this)).SendMailWithAttachmentAsync(inValue);
        }
    }
}
