//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daisybrand.forecaster.Services.Forecaster {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/AA_Forecaster.Model")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal _A_PULLS_FROM_CURRENT_FORECASTField;
        
        private string ACCOUTNNUMk__BackingFieldField;
        
        private decimal B_SECOND_WEEK_FORECASTk__BackingFieldField;
        
        private decimal CURRENT_FORECASTk__BackingFieldField;
        
        private string CUSTOMER_IDk__BackingFieldField;
        
        private decimal C_THIRD_WEEK_FORECASTk__BackingFieldField;
        
        private System.DayOfWeek[] DAYS_IN_WEEKk__BackingFieldField;
        
        private System.DateTime DELIVERY_DATEk__BackingFieldField;
        
        private decimal FIFTH_WEEK_FORECASTk__BackingFieldField;
        
        private string FORMULAk__BackingFieldField;
        
        private decimal FORTH_WEEK_FORECASTk__BackingFieldField;
        
        private decimal H_ON_HAND_DAY_OF_ORDERk__BackingFieldField;
        
        private decimal III_DAYS_QS_INCLUDING_AND_AFTER_ORDER_DAYk__BackingFieldField;
        
        private decimal II_DAYS_852_IS_REPORTEDk__BackingFieldField;
        
        private decimal IV_DAYS_QS_BEFORE_AND_INCLUDING_ORDER_DELIVERY_DAYk__BackingFieldField;
        
        private decimal I_ON_ORDER_DAY_OF_ORDERk__BackingFieldField;
        
        private decimal I_SAFETY_STOCK_DAYSk__BackingFieldField;
        
        private System.DateTime ORDER_DATEk__BackingFieldField;
        
        private int ORDER_TO_DELIVERYk__BackingFieldField;
        
        private decimal QS_UP_TO_DATEk__BackingFieldField;
        
        private decimal SAFETY_STOCKk__BackingFieldField;
        
        private daisybrand.forecaster.Services.Forecaster.FORECASTER_CUSTOMER_SETTINGS SETTINGk__BackingFieldField;
        
        private daisybrand.forecaster.Services.Forecaster.VMI_Get_Customers_SkuIds_Result[] SKUSk__BackingFieldField;
        
        private string SKUk__BackingFieldField;
        
        private System.Collections.Generic.Dictionary<string, decimal> SUGGESTED_ORDERSk__BackingFieldField;
        
        private decimal SUGGESTED_ORDERk__BackingFieldField;
        
        private decimal V_DAYS_QS_AFTER_ORDER_DELIVERY_DAY_AT_DCk__BackingFieldField;
        
        private bool WILL_COVER_OREDER_DATEk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _A_PULLS_FROM_CURRENT_FORECAST {
            get {
                return this._A_PULLS_FROM_CURRENT_FORECASTField;
            }
            set {
                if ((this._A_PULLS_FROM_CURRENT_FORECASTField.Equals(value) != true)) {
                    this._A_PULLS_FROM_CURRENT_FORECASTField = value;
                    this.RaisePropertyChanged("_A_PULLS_FROM_CURRENT_FORECAST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ACCOUTNNUM>k__BackingField", IsRequired=true)]
        public string ACCOUTNNUMk__BackingField {
            get {
                return this.ACCOUTNNUMk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ACCOUTNNUMk__BackingFieldField, value) != true)) {
                    this.ACCOUTNNUMk__BackingFieldField = value;
                    this.RaisePropertyChanged("ACCOUTNNUMk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<B_SECOND_WEEK_FORECAST>k__BackingField", IsRequired=true)]
        public decimal B_SECOND_WEEK_FORECASTk__BackingField {
            get {
                return this.B_SECOND_WEEK_FORECASTk__BackingFieldField;
            }
            set {
                if ((this.B_SECOND_WEEK_FORECASTk__BackingFieldField.Equals(value) != true)) {
                    this.B_SECOND_WEEK_FORECASTk__BackingFieldField = value;
                    this.RaisePropertyChanged("B_SECOND_WEEK_FORECASTk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CURRENT_FORECAST>k__BackingField", IsRequired=true)]
        public decimal CURRENT_FORECASTk__BackingField {
            get {
                return this.CURRENT_FORECASTk__BackingFieldField;
            }
            set {
                if ((this.CURRENT_FORECASTk__BackingFieldField.Equals(value) != true)) {
                    this.CURRENT_FORECASTk__BackingFieldField = value;
                    this.RaisePropertyChanged("CURRENT_FORECASTk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CUSTOMER_ID>k__BackingField", IsRequired=true)]
        public string CUSTOMER_IDk__BackingField {
            get {
                return this.CUSTOMER_IDk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CUSTOMER_IDk__BackingFieldField, value) != true)) {
                    this.CUSTOMER_IDk__BackingFieldField = value;
                    this.RaisePropertyChanged("CUSTOMER_IDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<C_THIRD_WEEK_FORECAST>k__BackingField", IsRequired=true)]
        public decimal C_THIRD_WEEK_FORECASTk__BackingField {
            get {
                return this.C_THIRD_WEEK_FORECASTk__BackingFieldField;
            }
            set {
                if ((this.C_THIRD_WEEK_FORECASTk__BackingFieldField.Equals(value) != true)) {
                    this.C_THIRD_WEEK_FORECASTk__BackingFieldField = value;
                    this.RaisePropertyChanged("C_THIRD_WEEK_FORECASTk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DAYS_IN_WEEK>k__BackingField", IsRequired=true)]
        public System.DayOfWeek[] DAYS_IN_WEEKk__BackingField {
            get {
                return this.DAYS_IN_WEEKk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DAYS_IN_WEEKk__BackingFieldField, value) != true)) {
                    this.DAYS_IN_WEEKk__BackingFieldField = value;
                    this.RaisePropertyChanged("DAYS_IN_WEEKk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DELIVERY_DATE>k__BackingField", IsRequired=true)]
        public System.DateTime DELIVERY_DATEk__BackingField {
            get {
                return this.DELIVERY_DATEk__BackingFieldField;
            }
            set {
                if ((this.DELIVERY_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.DELIVERY_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("DELIVERY_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FIFTH_WEEK_FORECAST>k__BackingField", IsRequired=true)]
        public decimal FIFTH_WEEK_FORECASTk__BackingField {
            get {
                return this.FIFTH_WEEK_FORECASTk__BackingFieldField;
            }
            set {
                if ((this.FIFTH_WEEK_FORECASTk__BackingFieldField.Equals(value) != true)) {
                    this.FIFTH_WEEK_FORECASTk__BackingFieldField = value;
                    this.RaisePropertyChanged("FIFTH_WEEK_FORECASTk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FORMULA>k__BackingField", IsRequired=true)]
        public string FORMULAk__BackingField {
            get {
                return this.FORMULAk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FORMULAk__BackingFieldField, value) != true)) {
                    this.FORMULAk__BackingFieldField = value;
                    this.RaisePropertyChanged("FORMULAk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FORTH_WEEK_FORECAST>k__BackingField", IsRequired=true)]
        public decimal FORTH_WEEK_FORECASTk__BackingField {
            get {
                return this.FORTH_WEEK_FORECASTk__BackingFieldField;
            }
            set {
                if ((this.FORTH_WEEK_FORECASTk__BackingFieldField.Equals(value) != true)) {
                    this.FORTH_WEEK_FORECASTk__BackingFieldField = value;
                    this.RaisePropertyChanged("FORTH_WEEK_FORECASTk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<H_ON_HAND_DAY_OF_ORDER>k__BackingField", IsRequired=true)]
        public decimal H_ON_HAND_DAY_OF_ORDERk__BackingField {
            get {
                return this.H_ON_HAND_DAY_OF_ORDERk__BackingFieldField;
            }
            set {
                if ((this.H_ON_HAND_DAY_OF_ORDERk__BackingFieldField.Equals(value) != true)) {
                    this.H_ON_HAND_DAY_OF_ORDERk__BackingFieldField = value;
                    this.RaisePropertyChanged("H_ON_HAND_DAY_OF_ORDERk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<III_DAYS_QS_INCLUDING_AND_AFTER_ORDER_DAY>k__BackingField", IsRequired=true)]
        public decimal III_DAYS_QS_INCLUDING_AND_AFTER_ORDER_DAYk__BackingField {
            get {
                return this.III_DAYS_QS_INCLUDING_AND_AFTER_ORDER_DAYk__BackingFieldField;
            }
            set {
                if ((this.III_DAYS_QS_INCLUDING_AND_AFTER_ORDER_DAYk__BackingFieldField.Equals(value) != true)) {
                    this.III_DAYS_QS_INCLUDING_AND_AFTER_ORDER_DAYk__BackingFieldField = value;
                    this.RaisePropertyChanged("III_DAYS_QS_INCLUDING_AND_AFTER_ORDER_DAYk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<II_DAYS_852_IS_REPORTED>k__BackingField", IsRequired=true)]
        public decimal II_DAYS_852_IS_REPORTEDk__BackingField {
            get {
                return this.II_DAYS_852_IS_REPORTEDk__BackingFieldField;
            }
            set {
                if ((this.II_DAYS_852_IS_REPORTEDk__BackingFieldField.Equals(value) != true)) {
                    this.II_DAYS_852_IS_REPORTEDk__BackingFieldField = value;
                    this.RaisePropertyChanged("II_DAYS_852_IS_REPORTEDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IV_DAYS_QS_BEFORE_AND_INCLUDING_ORDER_DELIVERY_DAY>k__BackingField", IsRequired=true)]
        public decimal IV_DAYS_QS_BEFORE_AND_INCLUDING_ORDER_DELIVERY_DAYk__BackingField {
            get {
                return this.IV_DAYS_QS_BEFORE_AND_INCLUDING_ORDER_DELIVERY_DAYk__BackingFieldField;
            }
            set {
                if ((this.IV_DAYS_QS_BEFORE_AND_INCLUDING_ORDER_DELIVERY_DAYk__BackingFieldField.Equals(value) != true)) {
                    this.IV_DAYS_QS_BEFORE_AND_INCLUDING_ORDER_DELIVERY_DAYk__BackingFieldField = value;
                    this.RaisePropertyChanged("IV_DAYS_QS_BEFORE_AND_INCLUDING_ORDER_DELIVERY_DAYk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<I_ON_ORDER_DAY_OF_ORDER>k__BackingField", IsRequired=true)]
        public decimal I_ON_ORDER_DAY_OF_ORDERk__BackingField {
            get {
                return this.I_ON_ORDER_DAY_OF_ORDERk__BackingFieldField;
            }
            set {
                if ((this.I_ON_ORDER_DAY_OF_ORDERk__BackingFieldField.Equals(value) != true)) {
                    this.I_ON_ORDER_DAY_OF_ORDERk__BackingFieldField = value;
                    this.RaisePropertyChanged("I_ON_ORDER_DAY_OF_ORDERk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<I_SAFETY_STOCK_DAYS>k__BackingField", IsRequired=true)]
        public decimal I_SAFETY_STOCK_DAYSk__BackingField {
            get {
                return this.I_SAFETY_STOCK_DAYSk__BackingFieldField;
            }
            set {
                if ((this.I_SAFETY_STOCK_DAYSk__BackingFieldField.Equals(value) != true)) {
                    this.I_SAFETY_STOCK_DAYSk__BackingFieldField = value;
                    this.RaisePropertyChanged("I_SAFETY_STOCK_DAYSk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ORDER_DATE>k__BackingField", IsRequired=true)]
        public System.DateTime ORDER_DATEk__BackingField {
            get {
                return this.ORDER_DATEk__BackingFieldField;
            }
            set {
                if ((this.ORDER_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.ORDER_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ORDER_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ORDER_TO_DELIVERY>k__BackingField", IsRequired=true)]
        public int ORDER_TO_DELIVERYk__BackingField {
            get {
                return this.ORDER_TO_DELIVERYk__BackingFieldField;
            }
            set {
                if ((this.ORDER_TO_DELIVERYk__BackingFieldField.Equals(value) != true)) {
                    this.ORDER_TO_DELIVERYk__BackingFieldField = value;
                    this.RaisePropertyChanged("ORDER_TO_DELIVERYk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<QS_UP_TO_DATE>k__BackingField", IsRequired=true)]
        public decimal QS_UP_TO_DATEk__BackingField {
            get {
                return this.QS_UP_TO_DATEk__BackingFieldField;
            }
            set {
                if ((this.QS_UP_TO_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.QS_UP_TO_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("QS_UP_TO_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SAFETY_STOCK>k__BackingField", IsRequired=true)]
        public decimal SAFETY_STOCKk__BackingField {
            get {
                return this.SAFETY_STOCKk__BackingFieldField;
            }
            set {
                if ((this.SAFETY_STOCKk__BackingFieldField.Equals(value) != true)) {
                    this.SAFETY_STOCKk__BackingFieldField = value;
                    this.RaisePropertyChanged("SAFETY_STOCKk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SETTING>k__BackingField", IsRequired=true)]
        public daisybrand.forecaster.Services.Forecaster.FORECASTER_CUSTOMER_SETTINGS SETTINGk__BackingField {
            get {
                return this.SETTINGk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SETTINGk__BackingFieldField, value) != true)) {
                    this.SETTINGk__BackingFieldField = value;
                    this.RaisePropertyChanged("SETTINGk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SKUS>k__BackingField", IsRequired=true)]
        public daisybrand.forecaster.Services.Forecaster.VMI_Get_Customers_SkuIds_Result[] SKUSk__BackingField {
            get {
                return this.SKUSk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUSk__BackingFieldField, value) != true)) {
                    this.SKUSk__BackingFieldField = value;
                    this.RaisePropertyChanged("SKUSk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SKU>k__BackingField", IsRequired=true)]
        public string SKUk__BackingField {
            get {
                return this.SKUk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUk__BackingFieldField, value) != true)) {
                    this.SKUk__BackingFieldField = value;
                    this.RaisePropertyChanged("SKUk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SUGGESTED_ORDERS>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, decimal> SUGGESTED_ORDERSk__BackingField {
            get {
                return this.SUGGESTED_ORDERSk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SUGGESTED_ORDERSk__BackingFieldField, value) != true)) {
                    this.SUGGESTED_ORDERSk__BackingFieldField = value;
                    this.RaisePropertyChanged("SUGGESTED_ORDERSk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SUGGESTED_ORDER>k__BackingField", IsRequired=true)]
        public decimal SUGGESTED_ORDERk__BackingField {
            get {
                return this.SUGGESTED_ORDERk__BackingFieldField;
            }
            set {
                if ((this.SUGGESTED_ORDERk__BackingFieldField.Equals(value) != true)) {
                    this.SUGGESTED_ORDERk__BackingFieldField = value;
                    this.RaisePropertyChanged("SUGGESTED_ORDERk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<V_DAYS_QS_AFTER_ORDER_DELIVERY_DAY_AT_DC>k__BackingField", IsRequired=true)]
        public decimal V_DAYS_QS_AFTER_ORDER_DELIVERY_DAY_AT_DCk__BackingField {
            get {
                return this.V_DAYS_QS_AFTER_ORDER_DELIVERY_DAY_AT_DCk__BackingFieldField;
            }
            set {
                if ((this.V_DAYS_QS_AFTER_ORDER_DELIVERY_DAY_AT_DCk__BackingFieldField.Equals(value) != true)) {
                    this.V_DAYS_QS_AFTER_ORDER_DELIVERY_DAY_AT_DCk__BackingFieldField = value;
                    this.RaisePropertyChanged("V_DAYS_QS_AFTER_ORDER_DELIVERY_DAY_AT_DCk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WILL_COVER_OREDER_DATE>k__BackingField", IsRequired=true)]
        public bool WILL_COVER_OREDER_DATEk__BackingField {
            get {
                return this.WILL_COVER_OREDER_DATEk__BackingFieldField;
            }
            set {
                if ((this.WILL_COVER_OREDER_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.WILL_COVER_OREDER_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("WILL_COVER_OREDER_DATEk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FORECASTER_CUSTOMER_SETTINGS", Namespace="http://schemas.datacontract.org/2004/07/AA_Forecaster.Entities")]
    [System.SerializableAttribute()]
    public partial class FORECASTER_CUSTOMER_SETTINGS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMMENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CUSTOMER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENTERED_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LAST_UPDATEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LINKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> REPORTING_DAYSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPORTING_ENDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPORTING_STARTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STORE_COUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> WILL_COVER_ORDER_DATEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMMENT {
            get {
                return this.COMMENTField;
            }
            set {
                if ((object.ReferenceEquals(this.COMMENTField, value) != true)) {
                    this.COMMENTField = value;
                    this.RaisePropertyChanged("COMMENT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CUSTOMER_ID {
            get {
                return this.CUSTOMER_IDField;
            }
            set {
                if ((this.CUSTOMER_IDField.Equals(value) != true)) {
                    this.CUSTOMER_IDField = value;
                    this.RaisePropertyChanged("CUSTOMER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENTERED_BY {
            get {
                return this.ENTERED_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.ENTERED_BYField, value) != true)) {
                    this.ENTERED_BYField = value;
                    this.RaisePropertyChanged("ENTERED_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LAST_UPDATED {
            get {
                return this.LAST_UPDATEDField;
            }
            set {
                if ((this.LAST_UPDATEDField.Equals(value) != true)) {
                    this.LAST_UPDATEDField = value;
                    this.RaisePropertyChanged("LAST_UPDATED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LINK {
            get {
                return this.LINKField;
            }
            set {
                if ((object.ReferenceEquals(this.LINKField, value) != true)) {
                    this.LINKField = value;
                    this.RaisePropertyChanged("LINK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> REPORTING_DAYS {
            get {
                return this.REPORTING_DAYSField;
            }
            set {
                if ((this.REPORTING_DAYSField.Equals(value) != true)) {
                    this.REPORTING_DAYSField = value;
                    this.RaisePropertyChanged("REPORTING_DAYS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPORTING_END {
            get {
                return this.REPORTING_ENDField;
            }
            set {
                if ((object.ReferenceEquals(this.REPORTING_ENDField, value) != true)) {
                    this.REPORTING_ENDField = value;
                    this.RaisePropertyChanged("REPORTING_END");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPORTING_START {
            get {
                return this.REPORTING_STARTField;
            }
            set {
                if ((object.ReferenceEquals(this.REPORTING_STARTField, value) != true)) {
                    this.REPORTING_STARTField = value;
                    this.RaisePropertyChanged("REPORTING_START");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STORE_COUNT {
            get {
                return this.STORE_COUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.STORE_COUNTField, value) != true)) {
                    this.STORE_COUNTField = value;
                    this.RaisePropertyChanged("STORE_COUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> WILL_COVER_ORDER_DATE {
            get {
                return this.WILL_COVER_ORDER_DATEField;
            }
            set {
                if ((this.WILL_COVER_ORDER_DATEField.Equals(value) != true)) {
                    this.WILL_COVER_ORDER_DATEField = value;
                    this.RaisePropertyChanged("WILL_COVER_ORDER_DATE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VMI_Get_Customers_SkuIds_Result", Namespace="http://schemas.datacontract.org/2004/07/AA_Forecaster.Entities")]
    [System.SerializableAttribute()]
    public partial class VMI_Get_Customers_SkuIds_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemUPCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToTPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemUPC {
            get {
                return this.ItemUPCField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemUPCField, value) != true)) {
                    this.ItemUPCField = value;
                    this.RaisePropertyChanged("ItemUPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToTP {
            get {
                return this.ShipToTPField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToTPField, value) != true)) {
                    this.ShipToTPField = value;
                    this.RaisePropertyChanged("ShipToTP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FORECASTER_KROGER_SALES_QTY_CASES", Namespace="http://schemas.datacontract.org/2004/07/AA_Forecaster.Entities")]
    [System.SerializableAttribute()]
    public partial class FORECASTER_KROGER_SALES_QTY_CASES : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivisionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ObjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SalesQuantityCasesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionNumber {
            get {
                return this.DivisionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionNumberField, value) != true)) {
                    this.DivisionNumberField = value;
                    this.RaisePropertyChanged("DivisionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ObjectID {
            get {
                return this.ObjectIDField;
            }
            set {
                if ((this.ObjectIDField.Equals(value) != true)) {
                    this.ObjectIDField = value;
                    this.RaisePropertyChanged("ObjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SalesQuantityCases {
            get {
                return this.SalesQuantityCasesField;
            }
            set {
                if ((this.SalesQuantityCasesField.Equals(value) != true)) {
                    this.SalesQuantityCasesField = value;
                    this.RaisePropertyChanged("SalesQuantityCases");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/AA_Forecaster")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Forecaster.IForecaster")]
    public interface IForecaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/Value", ReplyAction="http://tempuri.org/IForecaster/ValueResponse")]
        daisybrand.forecaster.Services.Forecaster.Customer Value(string customerNum, string userId, string connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/Value", ReplyAction="http://tempuri.org/IForecaster/ValueResponse")]
        System.Threading.Tasks.Task<daisybrand.forecaster.Services.Forecaster.Customer> ValueAsync(string customerNum, string userId, string connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetKrogerPOSData", ReplyAction="http://tempuri.org/IForecaster/GetKrogerPOSDataResponse")]
        daisybrand.forecaster.Services.Forecaster.FORECASTER_KROGER_SALES_QTY_CASES[] GetKrogerPOSData(string customerNum, string sku, string userId, string connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetKrogerPOSData", ReplyAction="http://tempuri.org/IForecaster/GetKrogerPOSDataResponse")]
        System.Threading.Tasks.Task<daisybrand.forecaster.Services.Forecaster.FORECASTER_KROGER_SALES_QTY_CASES[]> GetKrogerPOSDataAsync(string customerNum, string sku, string userId, string connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetDataTest", ReplyAction="http://tempuri.org/IForecaster/GetDataTestResponse")]
        string GetDataTest(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetDataTest", ReplyAction="http://tempuri.org/IForecaster/GetDataTestResponse")]
        System.Threading.Tasks.Task<string> GetDataTestAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IForecaster/GetDataUsingDataContractResponse")]
        daisybrand.forecaster.Services.Forecaster.CompositeType GetDataUsingDataContract(daisybrand.forecaster.Services.Forecaster.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IForecaster/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<daisybrand.forecaster.Services.Forecaster.CompositeType> GetDataUsingDataContractAsync(daisybrand.forecaster.Services.Forecaster.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IForecasterChannel : daisybrand.forecaster.Services.Forecaster.IForecaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForecasterClient : System.ServiceModel.ClientBase<daisybrand.forecaster.Services.Forecaster.IForecaster>, daisybrand.forecaster.Services.Forecaster.IForecaster {
        
        public ForecasterClient() {
        }
        
        public ForecasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForecasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForecasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForecasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public daisybrand.forecaster.Services.Forecaster.Customer Value(string customerNum, string userId, string connection) {
            return base.Channel.Value(customerNum, userId, connection);
        }
        
        public System.Threading.Tasks.Task<daisybrand.forecaster.Services.Forecaster.Customer> ValueAsync(string customerNum, string userId, string connection) {
            return base.Channel.ValueAsync(customerNum, userId, connection);
        }
        
        public daisybrand.forecaster.Services.Forecaster.FORECASTER_KROGER_SALES_QTY_CASES[] GetKrogerPOSData(string customerNum, string sku, string userId, string connection) {
            return base.Channel.GetKrogerPOSData(customerNum, sku, userId, connection);
        }
        
        public System.Threading.Tasks.Task<daisybrand.forecaster.Services.Forecaster.FORECASTER_KROGER_SALES_QTY_CASES[]> GetKrogerPOSDataAsync(string customerNum, string sku, string userId, string connection) {
            return base.Channel.GetKrogerPOSDataAsync(customerNum, sku, userId, connection);
        }
        
        public string GetDataTest(string message) {
            return base.Channel.GetDataTest(message);
        }
        
        public System.Threading.Tasks.Task<string> GetDataTestAsync(string message) {
            return base.Channel.GetDataTestAsync(message);
        }
        
        public daisybrand.forecaster.Services.Forecaster.CompositeType GetDataUsingDataContract(daisybrand.forecaster.Services.Forecaster.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<daisybrand.forecaster.Services.Forecaster.CompositeType> GetDataUsingDataContractAsync(daisybrand.forecaster.Services.Forecaster.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
