//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daisybrand.forecaster.Services.Promotions {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FORECASTER_PROMOTIONS", Namespace="http://schemas.datacontract.org/2004/07/Promotions.Entities")]
    [System.SerializableAttribute()]
    public partial class FORECASTER_PROMOTIONS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ConfirmedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ImportDatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndirectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndirectNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineItemStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ObjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerformanceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PerformanceTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromotionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeStatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmedBy {
            get {
                return this.ConfirmedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmedByField, value) != true)) {
                    this.ConfirmedByField = value;
                    this.RaisePropertyChanged("ConfirmedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ConfirmedDate {
            get {
                return this.ConfirmedDateField;
            }
            set {
                if ((this.ConfirmedDateField.Equals(value) != true)) {
                    this.ConfirmedDateField = value;
                    this.RaisePropertyChanged("ConfirmedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirectName {
            get {
                return this.DirectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectNameField, value) != true)) {
                    this.DirectNameField = value;
                    this.RaisePropertyChanged("DirectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirectNumber {
            get {
                return this.DirectNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectNumberField, value) != true)) {
                    this.DirectNumberField = value;
                    this.RaisePropertyChanged("DirectNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ImportDatetime {
            get {
                return this.ImportDatetimeField;
            }
            set {
                if ((this.ImportDatetimeField.Equals(value) != true)) {
                    this.ImportDatetimeField = value;
                    this.RaisePropertyChanged("ImportDatetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndirectName {
            get {
                return this.IndirectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IndirectNameField, value) != true)) {
                    this.IndirectNameField = value;
                    this.RaisePropertyChanged("IndirectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndirectNumber {
            get {
                return this.IndirectNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IndirectNumberField, value) != true)) {
                    this.IndirectNumberField = value;
                    this.RaisePropertyChanged("IndirectNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifiedBy {
            get {
                return this.LastModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastModifiedByField, value) != true)) {
                    this.LastModifiedByField = value;
                    this.RaisePropertyChanged("LastModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.LastModifiedDateField;
            }
            set {
                if ((this.LastModifiedDateField.Equals(value) != true)) {
                    this.LastModifiedDateField = value;
                    this.RaisePropertyChanged("LastModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineItemStatus {
            get {
                return this.LineItemStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.LineItemStatusField, value) != true)) {
                    this.LineItemStatusField = value;
                    this.RaisePropertyChanged("LineItemStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ObjectID {
            get {
                return this.ObjectIDField;
            }
            set {
                if ((this.ObjectIDField.Equals(value) != true)) {
                    this.ObjectIDField = value;
                    this.RaisePropertyChanged("ObjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PerformanceType {
            get {
                return this.PerformanceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformanceTypeField, value) != true)) {
                    this.PerformanceTypeField = value;
                    this.RaisePropertyChanged("PerformanceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerformanceTypeID {
            get {
                return this.PerformanceTypeIDField;
            }
            set {
                if ((this.PerformanceTypeIDField.Equals(value) != true)) {
                    this.PerformanceTypeIDField = value;
                    this.RaisePropertyChanged("PerformanceTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromotionNumber {
            get {
                return this.PromotionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PromotionNumberField, value) != true)) {
                    this.PromotionNumberField = value;
                    this.RaisePropertyChanged("PromotionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKUID {
            get {
                return this.SKUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUIDField, value) != true)) {
                    this.SKUIDField = value;
                    this.RaisePropertyChanged("SKUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeStatusCode {
            get {
                return this.TradeStatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeStatusCodeField, value) != true)) {
                    this.TradeStatusCodeField = value;
                    this.RaisePropertyChanged("TradeStatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Promotions")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Promotions.IForecaster")]
    public interface IForecaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetDataBySku", ReplyAction="http://tempuri.org/IForecaster/GetDataBySkuResponse")]
        daisybrand.forecaster.Services.Promotions.FORECASTER_PROMOTIONS[] GetDataBySku(string customerNum, string sku, string connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetDataBySku", ReplyAction="http://tempuri.org/IForecaster/GetDataBySkuResponse")]
        System.Threading.Tasks.Task<daisybrand.forecaster.Services.Promotions.FORECASTER_PROMOTIONS[]> GetDataBySkuAsync(string customerNum, string sku, string connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetData", ReplyAction="http://tempuri.org/IForecaster/GetDataResponse")]
        daisybrand.forecaster.Services.Promotions.FORECASTER_PROMOTIONS[] GetData(string customerNum, string connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetData", ReplyAction="http://tempuri.org/IForecaster/GetDataResponse")]
        System.Threading.Tasks.Task<daisybrand.forecaster.Services.Promotions.FORECASTER_PROMOTIONS[]> GetDataAsync(string customerNum, string connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetDataTest", ReplyAction="http://tempuri.org/IForecaster/GetDataTestResponse")]
        string GetDataTest(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetDataTest", ReplyAction="http://tempuri.org/IForecaster/GetDataTestResponse")]
        System.Threading.Tasks.Task<string> GetDataTestAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IForecaster/GetDataUsingDataContractResponse")]
        daisybrand.forecaster.Services.Promotions.CompositeType GetDataUsingDataContract(daisybrand.forecaster.Services.Promotions.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecaster/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IForecaster/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<daisybrand.forecaster.Services.Promotions.CompositeType> GetDataUsingDataContractAsync(daisybrand.forecaster.Services.Promotions.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IForecasterChannel : daisybrand.forecaster.Services.Promotions.IForecaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForecasterClient : System.ServiceModel.ClientBase<daisybrand.forecaster.Services.Promotions.IForecaster>, daisybrand.forecaster.Services.Promotions.IForecaster {
        
        public ForecasterClient() {
        }
        
        public ForecasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForecasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForecasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForecasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public daisybrand.forecaster.Services.Promotions.FORECASTER_PROMOTIONS[] GetDataBySku(string customerNum, string sku, string connection) {
            return base.Channel.GetDataBySku(customerNum, sku, connection);
        }
        
        public System.Threading.Tasks.Task<daisybrand.forecaster.Services.Promotions.FORECASTER_PROMOTIONS[]> GetDataBySkuAsync(string customerNum, string sku, string connection) {
            return base.Channel.GetDataBySkuAsync(customerNum, sku, connection);
        }
        
        public daisybrand.forecaster.Services.Promotions.FORECASTER_PROMOTIONS[] GetData(string customerNum, string connection) {
            return base.Channel.GetData(customerNum, connection);
        }
        
        public System.Threading.Tasks.Task<daisybrand.forecaster.Services.Promotions.FORECASTER_PROMOTIONS[]> GetDataAsync(string customerNum, string connection) {
            return base.Channel.GetDataAsync(customerNum, connection);
        }
        
        public string GetDataTest(string message) {
            return base.Channel.GetDataTest(message);
        }
        
        public System.Threading.Tasks.Task<string> GetDataTestAsync(string message) {
            return base.Channel.GetDataTestAsync(message);
        }
        
        public daisybrand.forecaster.Services.Promotions.CompositeType GetDataUsingDataContract(daisybrand.forecaster.Services.Promotions.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<daisybrand.forecaster.Services.Promotions.CompositeType> GetDataUsingDataContractAsync(daisybrand.forecaster.Services.Promotions.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
